### ISSUE TITLE
import acareeg

### ISSUE THREAD

**Issue by scott-huberty** [christian-oreilly/acareeg#4]
Maybe an additional requirement should be listed: `OpenGL-accelerate`. Not having this installed won't result in an error, but will result in a warning as follows:

`INFO - 2021-06-25 15:14:48,240 - acceleratesupport - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'`

**Comment by christian-oreilly** [comment]
Thanks for bringing that up, but this is actually not a dependency of acareeg, it is a dependency of one of the packages used by acareeg (probably MNE). Because of that, and because it is not an error but just a warning, I would not set it as an explicit requirement. You generally want to keep the requirements to a minimum for different reasons. 

I will keep this issue open though not for aceleratesupport but for the improvement of the requirements in general, which are currently not installed automatically by pip.
